### ISSUE TITLE
Poll buttons stay visible after a user has had Berry

### ISSUE THREAD

**Issue by Atte** [BTDev/BerryTube#13]

**Comment by Squirrel623** [comment]
Do you have any information to help reproduce this?

Are the "Poll buttons" referenced in the issue title the "New Poll" and "Close Active Poll" buttons below chat? If not, what do you mean by "Poll buttons"?

If so, I don't think I can reproduce this from what I have tried. I have tried giving berry back to the server via the "Give server berry" button, and as admin I have tried giving berry to a different user. Both times the two poll buttons seem to disappear on the original berry user's page. 

Is there another way to lose berry that I don't know of, or is there something special that needs to be done to trigger the bug? My dev setup is completely vanilla (no settings changed, no plugins or userscripts added/enabled) so there shouldn't be anything related to that causing this.

Sorry for any stupid questions, I haven't been berry before so I'm not familiar with how admin/mod/berry things work.

**Comment by Smidqe** [comment]
Yes those are what I consider poll buttons. 

It is possible that this is not an issue within BT itself, but on my own userscript.

**Comment by Atte** [comment]
Yeah this doesn't seem to be an issue anymore.
