### ISSUE TITLE
Flair field in chatMsg event is either a string or a number

### ISSUE THREAD

**Issue by Atte** [BTDev/BerryTube#17]
If the flair id is 0 it's a number, otherwise it's a string.

**Comment by Smidqe** [comment]
From what I've also noticed is that 0 can also be a string, it doesn't follow any pattern that I could find out.

**Comment by Smidqe** [comment]
https://github.com/BTDev/BerryTube/blob/master/web/js/init.js#L2056 

The problem happens when the flair is loaded from storage, if it was set after login it would appear as a number, otherwise it would be a string.
