### ISSUE TITLE
Handle failed age restricted YT embeds

### ISSUE THREAD

**Issue by Atte** [BTDev/BerryTube#45]
YouTube has broken embeds for age restricted videos. Handle them gracefully instead of breaking the tube player. Probably just check server-side if the video can be embedded, and abort the queue/play operation if not. Preferably show the user a message explaining why.

Check functionality both for 18+ videos and for "for kids" videos. Check functionality when a video is restricted when it's queued, and when it's not restricted when queued but becomes restricted before playing.

**Comment by Smidqe** [comment]
Youtube API has ytAgeRestricted option in contentDetails.contentRating.ytRating:
[https://developers.google.com/youtube/v3/docs/videos](https://developers.google.com/youtube/v3/docs/videos)

So it's trivial for checking age restriction for new videos, for existing videos it'll be more difficult
